//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leases
    {
        public Leases()
        {
            this.Payments = new HashSet<Payments>();
            this.LeaseHistory = new HashSet<LeaseHistory>();
        }
    
        public int LeaseID { get; set; }
        public string LeaseNumber { get; set; }
        public int PropertyID { get; set; }
        public int TenantID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal MonthlyAmount { get; set; }
        public string Status { get; set; }
        public string TerminationReason { get; set; }
        public string ConsentDocumentPath { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Tenants Tenants { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<LeaseHistory> LeaseHistory { get; set; }
    }
}
