//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Leases = new HashSet<Leases>();
        }
    
        public int PropertyID { get; set; }
        public string Address { get; set; }
        public decimal Area { get; set; }
        public string PropertyType { get; set; }
        public string Status { get; set; }
        public decimal MonthlyRent { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<Leases> Leases { get; set; }
    }
}
