//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RieltorEntities : DbContext
    {
        private static RieltorEntities _context;

        public static RieltorEntities GetContext()
        {
            if( _context == null )
                _context = new RieltorEntities();
            return _context;
        }

        public RieltorEntities()
            : base("name=RieltorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Leases> Leases { get; set; }
        public DbSet<Payments> Payments { get; set; }
        public DbSet<Property> Property { get; set; }
        public DbSet<Tenants> Tenants { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
