//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenants
    {
        public Tenants()
        {
            this.Leases = new HashSet<Leases>();
        }
    
        public int TenantID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string INN { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Leases> Leases { get; set; }
    }
}
